# Generated by Django 5.0.1 on 2024-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='count1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
