# Generated by Django 5.0.1 on 2024-01-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_remove_authormodel_count1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='count2',
        ),
    ]
